// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: grpc/warehouse.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "llm";

export interface AskRequest {
  question: string;
}

export interface AskResponse {
  answer: string;
}

function createBaseAskRequest(): AskRequest {
  return { question: "" };
}

export const AskRequest: MessageFns<AskRequest> = {
  encode(message: AskRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.question !== "") {
      writer.uint32(10).string(message.question);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AskRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAskRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.question = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AskRequest {
    return { question: isSet(object.question) ? globalThis.String(object.question) : "" };
  },

  toJSON(message: AskRequest): unknown {
    const obj: any = {};
    if (message.question !== "") {
      obj.question = message.question;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AskRequest>, I>>(base?: I): AskRequest {
    return AskRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AskRequest>, I>>(object: I): AskRequest {
    const message = createBaseAskRequest();
    message.question = object.question ?? "";
    return message;
  },
};

function createBaseAskResponse(): AskResponse {
  return { answer: "" };
}

export const AskResponse: MessageFns<AskResponse> = {
  encode(message: AskResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.answer !== "") {
      writer.uint32(10).string(message.answer);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AskResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAskResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.answer = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AskResponse {
    return { answer: isSet(object.answer) ? globalThis.String(object.answer) : "" };
  },

  toJSON(message: AskResponse): unknown {
    const obj: any = {};
    if (message.answer !== "") {
      obj.answer = message.answer;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AskResponse>, I>>(base?: I): AskResponse {
    return AskResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AskResponse>, I>>(object: I): AskResponse {
    const message = createBaseAskResponse();
    message.answer = object.answer ?? "";
    return message;
  },
};

export type LLMServiceService = typeof LLMServiceService;
export const LLMServiceService = {
  ask: {
    path: "/llm.LLMService/Ask",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AskRequest): Buffer => Buffer.from(AskRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AskRequest => AskRequest.decode(value),
    responseSerialize: (value: AskResponse): Buffer => Buffer.from(AskResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): AskResponse => AskResponse.decode(value),
  },
} as const;

export interface LLMServiceServer extends UntypedServiceImplementation {
  ask: handleUnaryCall<AskRequest, AskResponse>;
}

export interface LLMServiceClient extends Client {
  ask(request: AskRequest, callback: (error: ServiceError | null, response: AskResponse) => void): ClientUnaryCall;
  ask(
    request: AskRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: AskResponse) => void,
  ): ClientUnaryCall;
  ask(
    request: AskRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: AskResponse) => void,
  ): ClientUnaryCall;
}

export const LLMServiceClient = makeGenericClientConstructor(LLMServiceService, "llm.LLMService") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): LLMServiceClient;
  service: typeof LLMServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
